[project]
name = "day-3"
version = "0.1.0"
description = "Social media agent"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.2",
    "openai>=2.1.0",
    "pymongo>=4.15.3",
    "python-dotenv>=1.2.1",
    "tavily>=1.1.0",
]
